[ARC-1919] created splash, login ,sign up and home screen layouts
GiorgiMamagulashvili16/TaskPlanner pull request #1
Opened 2021-11-24 08:10 UTC by GiorgiMamagulashvili16

https://spaceneobank.atlassian.net/browse/ARC-1919

2021-11-24 09:30 UTC, giorgiqemoklidze requested changes

2021-11-24 09:30 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/data/extension/TextViewExt.kt
> +    var startInd = 0
კონსტანტ ცვლადში გაიტანე გიო

2021-11-24 11:30 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/extension/TextViewExt.kt
> +    var startInd = 0
done

2021-11-25 07:45 UTC, AleksandreGalogreBaramidze approved these changes

2021-11-25 07:46 UTC, andguladzeshio approved these changes

2021-11-25 08:39 UTC, giorgiqemoklidze approved these changes

2021-11-25 08:51 UTC, AnaRusadze requested changes

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/util/Constants.kt
> +    const val START_INDEX_FOR_SPANNABLE_TEXT = 0
ამ ცვლადს მარტო ექსთენშენში თუ იყენებ, ჯობია რომ ექსთენშენის ნაწილი იყოს და ფრაივითი. ზოგადად კონსტანტების ცალკე ობიექტის შექმნის მუღამი ისაა, თუ შიგნით არსებულ კონსტანტებს მთელი აპლიკაციის მასშტაბით სხვადასხვა ადგილას იყენებ

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationFragment.kt
> +            binding.submitImageButton.isVisible = text?.isNotBlank() == true
აქ ვერ გავიგე ;დ

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTextInputLayout.kt
> +        editText = findViewById(R.id.rootEditText)
binding-ის ცვლადი გამოაცხადე და გაუტოლე ItemBinding.inflate(
            LayoutInflater.from(
                context
            ), this, true
        )
და აღარ დაგჭირდება findViewById

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTextInputLayout.kt
> +) : ConstraintLayout(context, attrs, defAttrs) {
EditText-ის შვილი რომ გახადო, maxLine, hint, inputtype თავისით გადმოყვება მშობლიდან და აღარ მოგიწევს შენი ხელით დამატება

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTextInputLayout.kt
> +) : ConstraintLayout(context, attrs, defAttrs) {
შინაარსობრივადაც ხო ედიტტექსტია როგორ მივხვდი?

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/home_screen/HomeFragment.kt
> +class HomeFragment : Fragment() {
ბეიზის შვილი უნდა იყოს

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/home_screen/HomeFragment.kt
> +        fun newInstance() = HomeFragment()
ეს რისთვის?

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/splash_screen/SplashFragment.kt
> +//        }
კომენტარი დაგრჩა

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/res/layout/home_fragment.xml
> +        android:text="Peter Parker"
tools text

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/res/layout/home_fragment.xml
> +        android:text="Android Developer"
tools text

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/res/layout/home_fragment.xml
> +        android:id="@+id/appCompatTextView"
აიდის ცუდი სახელია, უნდა აღნიშნავდეს კონკრეტულად რისია

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/res/layout/row_project_item.xml
> +        android:text="In progress"
სტრინგების რესურსებში გადაიტანე

2021-11-25 08:51 UTC, AnaRusadze commented on app/src/main/res/layout/splash_fragment.xml
> +        android:text="Task Planner"
სტრინგების რესურსში

2021-11-25 08:53 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTextInputLayout.kt
> +) : ConstraintLayout(context, attrs, defAttrs) {
არა text input layout  და text input edit text ის ერთობლიობაა :დ

2021-11-25 08:54 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/home_screen/HomeFragment.kt
> +class HomeFragment : Fragment() {
კოდის მხარეზე როგადავალ შევასწორებ ყველას

2021-11-25 08:54 UTC, GiorgiMamagulashvili16 commented on app/src/main/res/layout/splash_fragment.xml
> +        android:text="Task Planner"
ესენი საცდლად იყო და როგორც ჩანს წაშლა დამვიწყებია :დ

2021-11-25 08:56 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationFragment.kt
> +            binding.submitImageButton.isVisible = text?.isNotBlank() == true
ეს ედით ტექსტიში იუზერის ინპუტებს უყურებს :დ თუ რაიმე დაიწერება ბათონს შოუს უკეთებს თუარა აჰაიდებს

2021-11-25 09:15 UTC, merged