[/ARC-1932]Implemented user register/login
GiorgiMamagulashvili16/TaskPlanner pull request #2
Opened 2021-11-29 09:07 UTC by GiorgiMamagulashvili16

https://spaceneobank.atlassian.net/browse/ARC-1932

2021-11-29 09:20 UTC, AleksandreGalogreBaramidze approved these changes

2021-11-29 09:20 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/taskplanner/data/repository/auth/AuthRepository.kt
> +    suspend fun getCurrentUser():Resource<User>
ფერებში გაიტანე

2021-11-29 09:20 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/repository/auth/AuthRepository.kt
> +    suspend fun getCurrentUser():Resource<User>
სტრინგებში მგონი

2021-11-29 09:21 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/taskplanner/data/repository/auth/AuthRepository.kt
> +    suspend fun getCurrentUser():Resource<User>
არა, ფერებში უნდა

2021-11-29 09:23 UTC, andguladzeshio approved these changes

2021-11-29 09:36 UTC, giorgiqemoklidze approved these changes

2021-11-29 10:03 UTC, AnaRusadze requested changes

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val profileImageUrl: String ="",
ჯობია profile image url და job nullable გახადო

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/repository/auth/AuthRepositoryImpl.kt
> +                uid = result.get("uid") as String
ესენიც კონსტანტ ცვლადებში მიამატე ჯობია

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/login_screen/LoginFragment.kt
> +                        loadingProgressBar.isVisible = it.isLoading
loadingProgressBar.isVisible = it.isLoading ეს ნაწილი when-ის ნებისმიერ პირობაში შესრულდება, ამიტომ შეგიძლია ცალ-ცალკე აღარ დაუწერო ყველას

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationFragment.kt
> +                    binding.loadingProgressBar.isVisible = it.isLoading
აქაც იგივე რაც ლოგინის დროს

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationFragment.kt
> +            ) {
ეს ჩემი აზრით ექსთენშენი უნდა იყოს

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +    fun signUp(username: String, password: String, email: String, job: String,imageUri: Uri) =
მე შენ ადგილას რაც შეიძლება პატარ პატარა ფუნქციებად დავყოფდი, იმელს ცალკე დავჩეკავდი, პაროლს ცალკე, იუზერნეიმს ცალკე

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +    fun signUp(username: String, password: String, email: String, job: String,imageUri: Uri) =
პატარ - პატარა ფუნქციებით უფრო კიტხვადი გამოვა, დებაგინგიც მარტივი და სოლიდის სინგლ რესფონსიბილითი პრინციპსაც შეინარჩუნებდი

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +    fun signUp(username: String, password: String, email: String, job: String,imageUri: Uri) =
იმაზე ფიქრიც შეიძლება რომ ბეიზ ვიუმოდელი ხომ არ ჰქონდეს რეგისტრაციას და ლოგინს და ვალიდაციის ფუნქცია მისი ნაწილი იყოს? იმიტომ რომ დუბლიკაციებია ბევრი

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/base/BaseFragment.kt
> +    protected inline fun mediaPermissionRequest(
ბეიზ ფრაგმენტის ნაწილი რატოა ეს ყველაფერი? ფერმიშენს რამდენ ადგილას იყენებ?

2021-11-29 10:03 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/home_screen/HomeViewModel.kt
> +        Log.d("TESDA", "${response.data}")
ეს რას ნიშნავს?

2021-11-29 10:09 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/home_screen/HomeViewModel.kt
> +        Log.d("TESDA", "${response.data}")
ფაიერბეისიდან წამოსულ რისპონს ვუშვებ კონკრეტული სქრინის სტეიტში

2021-11-29 10:10 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/base/BaseFragment.kt
> +    protected inline fun mediaPermissionRequest(
მგონი არა ამ აპლიკაციაში, მარა ბევრგან რომ დამჭირდეს ბეისში გატანა შეცდომაა ამ ფუნქციონალის ?

2021-11-29 10:11 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +    fun signUp(username: String, password: String, email: String, job: String,imageUri: Uri) =
იმელის ჩეკზე ექსთენსენი მაქვს და სტრინგის ჩეკზეც შეიძლება მაგის გაკეთება. თუ თვითონ ვმში გულისხმობ ცალ-ცალკე ფუნქციებად დაყოფას?

2021-11-29 10:12 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/login_screen/LoginFragment.kt
> +                        loadingProgressBar.isVisible = it.isLoading
ეგრე მქონდა მაგრამ არ შედიოდა მაგ ლაინში, data კლასზე გადავაწყობ სქრინის სტეიტს და მოგვარდება

2021-11-29 10:14 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/repository/auth/AuthRepositoryImpl.kt
> +                uid = result.get("uid") as String
საცდელი ფუნქციაა შემდეგ ბრენჩზე გავმართავ ამას

2021-11-29 10:15 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val profileImageUrl: String ="",
job ოფშენალი მაქვს და მაგიტო გავაკეთე დეფოლტ ველიუ და იმიჯი როგორც ჩანს დამრჩა :დდ

2021-11-29 10:21 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val profileImageUrl: String ="",
ოფშენალი როა, ზუსტად მაგ შინაარსის გამო უნდა გააკეთო ნალებლი. ანუ თუ არ აქვს ჯობი, ნალი იქნება.

2021-11-29 10:21 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +    fun signUp(username: String, password: String, email: String, job: String,imageUri: Uri) =
ვმში ვგულისხმობ ცალ-ცალკე

2021-11-29 10:22 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val profileImageUrl: String ="",
აჰა თუ ფაიერსთორსი იღებს ნალს მაშინ გავხდი, ვცდი აბა

2021-11-29 10:28 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +    fun signUp(username: String, password: String, email: String, job: String,imageUri: Uri) =
ოქეი ვცდი

2021-11-29 10:35 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationFragment.kt
> +            ) {
done

2021-11-29 12:18 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationFragment.kt
> +                    binding.loadingProgressBar.isVisible = it.isLoading
done

2021-11-29 12:19 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/login_screen/LoginFragment.kt
> +                        loadingProgressBar.isVisible = it.isLoading
done

2021-11-29 13:09 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val profileImageUrl: String ="",
done

2021-11-29 14:26 UTC, AnaRusadze requested changes

2021-11-29 14:26 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/login_screen/LoginFragment.kt
> +                if (state.errorText != null) {
ამ იფში მხოლოდ მაშინ დაგჭირდება შემოსვლა თუ state.isSuccess არ იქნება. else if უნდა ეწეროს

2021-11-29 14:26 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationFragment.kt
> +                if (state.errorText != null) {
აქაც

2021-11-29 14:37 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/login_screen/LoginFragment.kt
> +                if (state.errorText != null) {
done

2021-11-29 14:37 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationFragment.kt
> +                if (state.errorText != null) {
done

2021-12-01 07:54 UTC, AnaRusadze requested changes

2021-12-01 07:54 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val uid: String,
uid სტრინგი უნდა იყოს თუ ინტი?

2021-12-01 07:54 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val job: String? = null
მერე იუზერ კლასს თავისი პროექტების სიაც დაუმატე

2021-12-01 07:54 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/login_screen/LoginViewModel.kt
> +            }
ჩემი რჩევაა რომ ცალ-ცალკე ფუნქციებად დაყო იმეილის პაროლის ვალიდაციები და შემდეგ უკვე ლოგინიც

2021-12-01 07:54 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +    fun signUp(username: String, password: String, email: String, job: String, imageUri: Uri) =
პირდაპირ იუზერის კლასის პარამეტრი გადააწოდე

2021-12-01 07:54 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/base/BaseFragment.kt
> +    protected inline fun mediaPermissionRequest(
კლასი შექმენი, ManagePermission და მასში გაიტანე ეს ფუნქციონალი

2021-12-01 07:54 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/base/BaseFragment.kt
> +    protected inline fun mediaPermissionRequest(
ბეიზ ფრაგმენტში არუნდა იყოს

2021-12-01 07:54 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/home_screen/HomeViewModel.kt
> +        Log.d("TESDA", "${response.data}")
ლოგს ვგულისხმობ, "TESDA"ს კონკრეტულად

2021-12-01 08:05 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val uid: String,
სტრინგია ფაიერბეისიდან

2021-12-01 08:05 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val job: String? = null
კი შემდეგ პრ ებში.

2021-12-01 08:07 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/login_screen/LoginViewModel.kt
> +            }
კიდევ ჩავშალო სტრინგების ვალიდატორი ესეიგი?

2021-12-01 08:07 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +    fun signUp(username: String, password: String, email: String, job: String, imageUri: Uri) =
კი შემდეგ პრზე გასწორდება პროექტების პარამეტრებაც რომ დავამატებ

2021-12-01 08:50 UTC, merged