[ARC-1940]implemented project details screen, edit and delete project features
GiorgiMamagulashvili16/TaskPlanner pull request #4
Opened 2021-12-06 06:47 UTC by GiorgiMamagulashvili16

https://spaceneobank.atlassian.net/browse/ARC-1940

2021-12-06 15:01 UTC, AnaRusadze requested changes

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/model/Project.kt
> +    val projectId: String? = null,
რატო მიუმატე ნალები?

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/model/Task.kt
> +    val endTime: String? = null
ან აქ?

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/model/User.kt
> +    val profileImageUrl: String? = null,
ან აქ

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/data/repository/project/ProjectRepositoryImpl.kt
> +                    "projectTitle" to project.projectTitle,
ესენიც კონსტანტაში გადაიტანე

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +                            password
პაროლი რატო არაა იუზერის ნაწილი?

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/home_screen/ProjectsAdapter.kt
> +                    ContextCompat.getColor(
ექსთენშენი გააკეთე მაგის, კაი იქნება

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/ProjectStatus.kt
> +    DONE(title = "Done", color = R.color.light_green)
სათაურები სტრინგების რესურსებში გადაიტანე

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +                createSnackBar(state.errorText) {
სნეკბარის ფუნქცია ცალკე

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +                        dismiss()
დუბლირებული კოდია სნეკბარის

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +            with(project) {
with(binding.project)

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +                        AppCompatResources.getDrawable(
ექსთენშენი გააკეთე, კაი იქნება

2021-12-06 15:01 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +        private const val SUCCESSFULLY_EDITED_PROJECT_MESSAGE = "successfully edited project info"
ეს სტრინგების რესურსებში უნდა იყოს

2021-12-06 16:10 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/model/Project.kt
> +    val projectId: String? = null,
ფაიერსტორს ჭირდება დეფოლტ ველიუ რომ წამოვიღო ინფო

2021-12-06 16:10 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/authorization/registration_screen/RegistrationViewModel.kt
> +                            password
რავი :დ

2021-12-06 16:11 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/ProjectStatus.kt
> +    DONE(title = "Done", color = R.color.light_green)
სტრინგებიდან ვერ ამოვიღებ აქ მგონი, და კონსტანტებსაც არ იღებდა რატომღაც და მაგიტო დავტოვე ესე

2021-12-06 16:12 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +            with(project) {
არ იმუშავებს ბაინდინგი და პროჯექტი სხვადასხვა ობიექტებია

2021-12-06 16:12 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +        private const val SUCCESSFULLY_EDITED_PROJECT_MESSAGE = "successfully edited project info"
done

2021-12-06 17:15 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/ProjectStatus.kt
> +    DONE(title = "Done", color = R.color.light_green)
თვითონაც ხო კონსტანტია მგონი და მაგიტომ

2021-12-06 17:23 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +                        AppCompatResources.getDrawable(
done

2021-12-06 17:24 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +                        dismiss()
done

2021-12-06 17:24 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/project_detail/ProjectDetailFragment.kt
> +                createSnackBar(state.errorText) {
done

2021-12-06 17:24 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/home_screen/ProjectsAdapter.kt
> +                    ContextCompat.getColor(
done

2021-12-06 17:26 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/data/repository/project/ProjectRepositoryImpl.kt
> +                    "projectTitle" to project.projectTitle,
done

2021-12-08 12:43 UTC, AnaRusadze requested changes

2021-12-08 12:43 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/project_screen/ProjectStatus.kt
> +    DONE(title = "Done", color = R.color.light_green)
უბრალოდ R.sting.in_progress რესურსების სახით ჰქონდეს, ინტით და როდესაც მიწვდები მერე ამოიღებ getString-ით

2021-12-08 12:49 UTC, AnaRusadze approved these changes

2021-12-08 12:49 UTC, merged