[ARC-1947] code refactor
GiorgiMamagulashvili16/TaskPlanner pull request #6
Opened 2021-12-15 07:31 UTC by GiorgiMamagulashvili16

https://spaceneobank.atlassian.net/browse/ARC-1947

2021-12-15 10:39 UTC, AnaRusadze requested changes

2021-12-15 10:39 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/base/AuthBaseViewModel.kt
> +        if (user.profileImageUrl != null) {
ანუ სურათს ამოწმებ თუ ნალია, ეგრე ხვდები რო ლოგინის შემოწმებაა, თუ არადა რეგისტრაციის?

2021-12-15 10:39 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/base/AuthBaseViewModel.kt
> +                    listOf(user.email!!, user.password!!, user.username!!),
პაროლების შედარების შემოწმება გაქვს?

2021-12-15 10:39 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="end_time_of_task_is_more_than_end_time_of_project">End date of task is more than end date of project, try again</string>
თუ ძალიან გრძელი წინადადებაა, სტრინგის სახელი შინაარსობრივად დაარქვი, start date invalid error, end date invalide error მაგალითად

2021-12-15 10:39 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/base/ProjectBaseViewModel.kt
> +            is Project -> {
ჯობია, რომ setNewItemის ნაცვლად addNewProject და addNewTask ფუნქციები ცალ-ცალკე გქონდეს. იმიტომ რომ გამოძახების ადგილებში ზუსტად იცი რომლის დამატება გსურს და whenით შემოწმება დამატებითი ოპერაციაა

2021-12-15 10:39 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/base/ProjectBaseViewModel.kt
> +    private fun checkTaskEstimateDate(
ჯობია, რომ თარიღის შემოწმება პროექტის დამატების დროს კი არ იყოს, თვითონ თარიღის არჩევისას, არავალიდური თარიღები isNotClickable იყოს ან toast ამოვარდეს.

2021-12-15 10:39 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTaskNumberItem.kt
> +    private var textView: AppCompatTextView
ეს ზედმეტია როგორც მივხვდი

2021-12-15 10:39 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTaskNumberItem.kt
> +class CustomTaskNumberItem @JvmOverloads constructor(
სახელი Viewთი დააბოლოვე item-ის ნაცვლად

2021-12-15 11:31 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/base/AuthBaseViewModel.kt
> +        if (user.profileImageUrl != null) {
კი ეგრე მარა შევასწორებ

2021-12-15 11:45 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/base/AuthBaseViewModel.kt
> +        if (user.profileImageUrl != null) {
done

2021-12-15 11:45 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/base/AuthBaseViewModel.kt
> +                    listOf(user.email!!, user.password!!, user.username!!),
done

2021-12-15 11:45 UTC, GiorgiMamagulashvili16 commented on app/src/main/res/values/strings.xml
> +    <string name="end_time_of_task_is_more_than_end_time_of_project">End date of task is more than end date of project, try again</string>
done

2021-12-15 11:45 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/base/ProjectBaseViewModel.kt
> +            is Project -> {
done

2021-12-15 11:46 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/base/ProjectBaseViewModel.kt
> +    private fun checkTaskEstimateDate(
done

2021-12-15 11:46 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTaskNumberItem.kt
> +    private var textView: AppCompatTextView
done

2021-12-15 11:46 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTaskNumberItem.kt
> +class CustomTaskNumberItem @JvmOverloads constructor(
done

2021-12-15 11:59 UTC, AnaRusadze requested changes

2021-12-15 11:59 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTaskNumberView.kt
> +    private var textView: AppCompatTextView
ეს წაშალე

2021-12-15 12:05 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTaskNumberView.kt
> +    private var textView: AppCompatTextView
მჭირდება ეს ცვლადები კლასის ფუნქციებში

2021-12-15 12:07 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTaskNumberView.kt
> +    private var textView: AppCompatTextView
roundedBackgroundColor წავშალო თუ ყველა  ცვლადი? :დდდ

2021-12-15 12:08 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTaskNumberView.kt
> +    private var textView: AppCompatTextView
პირდაპირ statusTextView გამოიყენე, ახალი textView რატო გჭირდება?

2021-12-15 12:11 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/taskplanner/presentation/custom_view/CustomTaskNumberView.kt
> +    private var textView: AppCompatTextView
აა , მერე ფუნქციებისთვის როარ მეწოდებინა სათითაოდ,ეს text view ცვლადი შევქმენი და ინიციალიზაციას ვუკეთებ status text view ით :დ

2021-12-21 10:02 UTC, AnaRusadze approved these changes

2021-12-21 10:02 UTC, merged